# Configuration de base
title: "Ma Hacking Base"
description: "Un site dédié à l'apprentissage du hacking éthique."
theme: minima
url: "https://dikabraxis.github.io"
baseurl: ""

# Inclure tous les fichiers dans le dossier outils
include:
  - index.md

# Exclure certains fichiers inutiles lors du rendu
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Configuration des permaliens
permalink: pretty

# Configuration Markdown
markdown: kramdown
kramdown:
  input: GFM

# Désactiver les liens relatifs pour éviter les erreurs 404
relative_permalinks: false
